### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by jouvigrouvi** [worker8/TourGuide#116]
Fatal Exception: java.lang.NullPointerException
       at android.support.v7.widget.TooltipPopup.show(TooltipPopup.java:79)
       at android.support.v7.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:155)
       at android.support.v7.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:103)
       at android.view.View.performLongClick(View.java:4499)
       at android.widget.TextView.performLongClick(TextView.java:8578)
       at android.view.View$CheckForLongPress.run(View.java:18749)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jovanovski** [comment]
I also have this happening in my code quite a lot. Any ideas guys?

**Comment by jovikao** [comment]
Me too.

**Comment by jovikao** [comment]
@DaRkRaGe & @jovanovski 
I think this issue has been fixed by #120 
Update version to 1.0.19-SNAPSHOT@aar may fix it.
See https://issuetracker.google.com/issues/64594124 for the reason.
