### ISSUE TITLE
Failed resolution of: Lnet/i2p/android/ext/floatingactionbutton/FloatingActionButton

### ISSUE THREAD

**Issue by EhsanPM** [worker8/TourGuide#18]
When I try to put TourGuide in gradle file of my project if I include { transitive=true} It will not build and show:

Error:Execution failed for task ':dexDebug'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

So I omitted it and after that when I try to use it in a simple example I get this error message:

 java.lang.NoClassDefFoundError: Failed resolution of: Lnet/i2p/android/ext/floatingactionbutton/FloatingActionButton;
            at tourguide.tourguide.TourGuide.setupAndAddFABToFrameLayout(TourGuide.java:284)
            at tourguide.tourguide.TourGuide.access$700(TourGuide.java:26)
.
.
.

Any help?

**Comment by EhsanPM** [comment]
I deleted android-support-v4.jar and it is compiling without issues now.
